// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Context;

#nullable disable

namespace Repository.Context.Migrations
{
    [DbContext(typeof(EVSDbContext))]
<<<<<<<< Updated upstream:Repository/Context/Migrations/20251107085906_InitMigration.Designer.cs
    [Migration("20251107085906_InitMigration")]
========
    [Migration("20251110070532_InitMigration")]
>>>>>>>> Stashed changes:Repository/Context/Migrations/20251110070532_InitMigration.Designer.cs
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repository.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryDuration")
                        .HasColumnType("int");

                    b.Property<string>("BatteryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RentPricePerDay")
                        .HasColumnType("float");

                    b.Property<double>("RentPricePerDayWithDriver")
                        .HasColumnType("float");

                    b.Property<double>("RentPricePerHour")
                        .HasColumnType("float");

                    b.Property<double>("RentPricePerHourWithDriver")
                        .HasColumnType("float");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<string>("SizeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TrunkCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatteryDuration = 350,
                            BatteryType = "Lithium-Ion",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/tesla_model_3.jpg",
                            ImageUrl2 = "https://example.com/tesla_model_3.jpg",
                            ImageUrl3 = "https://example.com/tesla_model_3.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Model = "Tesla Model 3",
                            Name = "Model 3",
                            RentPricePerDay = 1000000.0,
                            RentPricePerDayWithDriver = 1400000.0,
                            RentPricePerHour = 45000.0,
                            RentPricePerHourWithDriver = 60000.0,
                            Seats = 5,
                            SizeType = "Sedan",
                            Status = 1,
                            TrunkCapacity = 425
                        },
                        new
                        {
                            Id = 2,
                            BatteryDuration = 240,
                            BatteryType = "Lithium-Ion",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/nissan_leaf.jpg",
                            ImageUrl2 = "https://example.com/nissan_leaf.jpg",
                            ImageUrl3 = "https://example.com/nissan_leaf.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Model = "Nissan Leaf",
                            Name = "Leaf",
                            RentPricePerDay = 800000.0,
                            RentPricePerDayWithDriver = 1200000.0,
                            RentPricePerHour = 35000.0,
                            RentPricePerHourWithDriver = 50000.0,
                            Seats = 5,
                            SizeType = "Hatchback",
                            Status = 1,
                            TrunkCapacity = 435
                        },
                        new
                        {
                            Id = 3,
                            BatteryDuration = 259,
                            BatteryType = "Lithium-Ion",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/chevrolet_bolt_ev.jpg",
                            ImageUrl2 = "https://example.com/chevrolet_bolt_ev.jpg",
                            ImageUrl3 = "https://example.com/chevrolet_bolt_ev.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Model = "Chevrolet Bolt EV",
                            Name = "Bolt EV",
                            RentPricePerDay = 900000.0,
                            RentPricePerDayWithDriver = 1300000.0,
                            RentPricePerHour = 40000.0,
                            RentPricePerHourWithDriver = 55000.0,
                            Seats = 5,
                            SizeType = "Hatchback",
                            Status = 1,
                            TrunkCapacity = 478
                        },
                        new
                        {
                            Id = 4,
                            BatteryDuration = 305,
                            BatteryType = "Lithium-Ion",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/hyundai_kona.jpg",
                            ImageUrl2 = "https://example.com/hyundai_kona.jpg",
                            ImageUrl3 = "https://example.com/hyundai_kona.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Model = "Hyundai Kona Electric",
                            Name = "Kona Electric",
                            RentPricePerDay = 900000.0,
                            RentPricePerDayWithDriver = 1300000.0,
                            RentPricePerHour = 40000.0,
                            RentPricePerHourWithDriver = 55000.0,
                            Seats = 5,
                            SizeType = "SUV",
                            Status = 1,
                            TrunkCapacity = 332
                        },
                        new
                        {
                            Id = 5,
                            BatteryDuration = 510,
                            BatteryType = "Lithium-Ion",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/kia_ev6.jpg",
                            ImageUrl2 = "https://example.com/kia_ev6.jpg",
                            ImageUrl3 = "https://example.com/kia_ev6.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Model = "Kia EV6",
                            Name = "EV6",
                            RentPricePerDay = 1200000.0,
                            RentPricePerDayWithDriver = 1600000.0,
                            RentPricePerHour = 55000.0,
                            RentPricePerHourWithDriver = 75000.0,
                            Seats = 5,
                            SizeType = "Crossover",
                            Status = 1,
                            TrunkCapacity = 480
                        },
                        new
                        {
                            Id = 6,
                            BatteryDuration = 285,
                            BatteryType = "Lithium-Ion",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/vf_e34.jpg",
                            ImageUrl2 = "https://example.com/vf_e34.jpg",
                            ImageUrl3 = "https://example.com/vf_e34.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Model = "VinFast VF e34",
                            Name = "VF e34",
                            RentPricePerDay = 850000.0,
                            RentPricePerDayWithDriver = 1150000.0,
                            RentPricePerHour = 38000.0,
                            RentPricePerHourWithDriver = 52000.0,
                            Seats = 5,
                            SizeType = "SUV",
                            Status = 1,
                            TrunkCapacity = 290
                        },
                        new
                        {
                            Id = 7,
                            BatteryDuration = 200,
                            BatteryType = "Lithium-Ion",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/bmw_i3.jpg",
                            ImageUrl2 = "https://example.com/bmw_i3.jpg",
                            ImageUrl3 = "https://example.com/bmw_i3.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Model = "BMW i3",
                            Name = "i3",
                            RentPricePerDay = 1100000.0,
                            RentPricePerDayWithDriver = 1450000.0,
                            RentPricePerHour = 50000.0,
                            RentPricePerHourWithDriver = 68000.0,
                            Seats = 4,
                            SizeType = "Hatchback",
                            Status = 1,
                            TrunkCapacity = 260
                        },
                        new
                        {
                            Id = 8,
                            BatteryDuration = 450,
                            BatteryType = "Lithium-Ion",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/porsche_taycan.jpg",
                            ImageUrl2 = "https://example.com/porsche_taycan.jpg",
                            ImageUrl3 = "https://example.com/porsche_taycan.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Model = "Porsche Taycan",
                            Name = "Taycan",
                            RentPricePerDay = 2500000.0,
                            RentPricePerDayWithDriver = 3000000.0,
                            RentPricePerHour = 100000.0,
                            RentPricePerHourWithDriver = 130000.0,
                            Seats = 4,
                            SizeType = "Sedan",
                            Status = 1,
                            TrunkCapacity = 366
                        },
                        new
                        {
                            Id = 9,
                            BatteryDuration = 410,
                            BatteryType = "Lithium-Ion",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/mercedes_eqc.jpg",
                            ImageUrl2 = "https://example.com/mercedes_eqc.jpg",
                            ImageUrl3 = "https://example.com/mercedes_eqc.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Model = "Mercedes EQC",
                            Name = "EQC",
                            RentPricePerDay = 1800000.0,
                            RentPricePerDayWithDriver = 2300000.0,
                            RentPricePerHour = 85000.0,
                            RentPricePerHourWithDriver = 110000.0,
                            Seats = 5,
                            SizeType = "SUV",
                            Status = 1,
                            TrunkCapacity = 500
                        },
                        new
                        {
                            Id = 10,
                            BatteryDuration = 430,
                            BatteryType = "Lithium-Ion",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/audi_etron.jpg",
                            ImageUrl2 = "https://example.com/audi_etron.jpg",
                            ImageUrl3 = "https://example.com/audi_etron.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Model = "Audi e-tron",
                            Name = "e-tron",
                            RentPricePerDay = 1700000.0,
                            RentPricePerDayWithDriver = 2200000.0,
                            RentPricePerHour = 80000.0,
                            RentPricePerHourWithDriver = 100000.0,
                            Seats = 5,
                            SizeType = "SUV",
                            Status = 1,
                            TrunkCapacity = 555
                        });
                });

            modelBuilder.Entity("Repository.Entities.CarDeliveryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryLevelStart")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("OdometerStart")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleConditionStart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrderId");

                    b.HasIndex("StaffId");

                    b.ToTable("CarDeliveryHistories");
                });

            modelBuilder.Entity("Repository.Entities.CarRentalLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("LocationId");

                    b.ToTable("CarRentalLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            IsDeleted = false,
                            LocationId = 1,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 4,
                            CarId = 4,
                            IsDeleted = false,
                            LocationId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 5,
                            CarId = 5,
                            IsDeleted = false,
                            LocationId = 3,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 6,
                            CarId = 6,
                            IsDeleted = false,
                            LocationId = 3,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 7,
                            CarId = 7,
                            IsDeleted = false,
                            LocationId = 4,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 8,
                            CarId = 8,
                            IsDeleted = false,
                            LocationId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 9,
                            CarId = 9,
                            IsDeleted = false,
                            LocationId = 5,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 10,
                            CarId = 10,
                            IsDeleted = false,
                            LocationId = 5,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 11,
                            CarId = 1,
                            IsDeleted = false,
                            LocationId = 6,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("Repository.Entities.CarReturnHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryLevelEnd")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("OdometerEnd")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleConditionEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrderId");

                    b.HasIndex("StaffId");

                    b.ToTable("CarReturnHistories");
                });

            modelBuilder.Entity("Repository.Entities.CitizenId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CitizenIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RentalOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CitizenIds");
                });

            modelBuilder.Entity("Repository.Entities.DriverLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RentalOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DriverLicenses");
                });

            modelBuilder.Entity("Repository.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RentalOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RentalOrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Xe mới, sạch sẽ và nhân viên hỗ trợ rất nhiệt tình.",
                            CreatedAt = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RentalOrderId = 1,
                            Title = "Dịch vụ tuyệt vời",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Giá thuê xe phù hợp, chất lượng xe tốt, pin đầy đủ.",
                            CreatedAt = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RentalOrderId = 2,
                            Title = "Giá hợp lý",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Chỉ mất vài phút để hoàn thành thủ tục thuê xe.",
                            CreatedAt = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RentalOrderId = 3,
                            Title = "Thủ tục nhanh chóng",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Nhân viên tư vấn rất chu đáo, hướng dẫn chi tiết khi nhận xe.",
                            CreatedAt = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RentalOrderId = 4,
                            Title = "Nhân viên thân thiện",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Content = "Xe điện chạy rất êm, tiết kiệm và thân thiện môi trường.",
                            CreatedAt = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RentalOrderId = 5,
                            Title = "Xe chạy êm",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Content = "Mọi thứ ổn, nhưng mong có thêm nhiều trạm sạc hơn ở trung tâm.",
                            CreatedAt = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RentalOrderId = 6,
                            Title = "Cần thêm trạm sạc",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Content = "Dịch vụ chuyên nghiệp, hệ thống đặt xe dễ dùng.",
                            CreatedAt = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RentalOrderId = 7,
                            Title = "Trải nghiệm tốt",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Content = "Tôi gặp vấn đề nhỏ về pin, nhân viên đã hỗ trợ rất nhanh.",
                            CreatedAt = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RentalOrderId = 8,
                            Title = "Hỗ trợ nhanh",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Content = "Xe mới, thiết kế hiện đại, rất hài lòng với chuyến đi.",
                            CreatedAt = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RentalOrderId = 9,
                            Title = "Xe đẹp",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Content = "Tôi sẽ tiếp tục thuê xe ở đây trong các chuyến công tác sau.",
                            CreatedAt = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RentalOrderId = 10,
                            Title = "Rất hài lòng",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Repository.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RentalOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Repository.Entities.RentalContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LesseeId")
                        .HasColumnType("int");

                    b.Property<int?>("LessorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentalDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RentalOrderId")
                        .HasColumnType("int");

                    b.Property<string>("RentalPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TerminationClause")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RentalContacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            LesseeId = 1,
                            LessorId = 2,
                            RentalDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalOrderId = 1,
                            RentalPeriod = "3 ngày",
                            ReturnDate = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TerminationClause = "Chấm dứt hợp đồng sớm sẽ chịu phí 10%."
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            LesseeId = 2,
                            LessorId = 3,
                            RentalDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalOrderId = 2,
                            RentalPeriod = "7 ngày",
                            ReturnDate = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TerminationClause = "Phí chấm dứt sớm: 15%."
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            LesseeId = 3,
                            LessorId = 1,
                            RentalDate = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalOrderId = 3,
                            RentalPeriod = "5 ngày",
                            ReturnDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TerminationClause = "Phải thông báo trước 24h để chấm dứt hợp đồng."
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            LesseeId = 4,
                            LessorId = 5,
                            RentalDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalOrderId = 4,
                            RentalPeriod = "2 ngày",
                            ReturnDate = new DateTime(2025, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TerminationClause = "Không hoàn tiền nếu hủy trong vòng 12h."
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            LesseeId = 5,
                            LessorId = 6,
                            RentalDate = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalOrderId = 5,
                            RentalPeriod = "10 ngày",
                            ReturnDate = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TerminationClause = "Phí hủy hợp đồng: 20% tổng giá trị."
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            LesseeId = 6,
                            LessorId = 7,
                            RentalDate = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalOrderId = 6,
                            RentalPeriod = "1 ngày",
                            ReturnDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TerminationClause = "Không hoàn tiền nếu hủy trong ngày thuê."
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            LesseeId = 7,
                            LessorId = 8,
                            RentalDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalOrderId = 7,
                            RentalPeriod = "4 ngày",
                            ReturnDate = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TerminationClause = "Có thể gia hạn thêm tối đa 2 ngày."
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            LesseeId = 8,
                            LessorId = 9,
                            RentalDate = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalOrderId = 8,
                            RentalPeriod = "6 ngày",
                            ReturnDate = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TerminationClause = "Không áp dụng hoàn tiền nếu xe bị hư hại."
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            LesseeId = 9,
                            LessorId = 10,
                            RentalDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalOrderId = 9,
                            RentalPeriod = "8 ngày",
                            ReturnDate = new DateTime(2025, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TerminationClause = "Có thể kết thúc sớm nhưng không hoàn phí thuê."
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            LesseeId = 10,
                            LessorId = 1,
                            RentalDate = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalOrderId = 10,
                            RentalPeriod = "3 ngày",
                            ReturnDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TerminationClause = "Hợp đồng sẽ tự động hết hạn sau ngày trả xe."
                        });
                });

            modelBuilder.Entity("Repository.Entities.RentalLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RentalLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Tran Hung Dao St, Ho Chi Minh City",
                            Coordinates = "10.7769,106.7009",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Downtown Rental Location"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Nguyen Cuu Phuc St, Ho Chi Minh City",
                            Coordinates = "10.7950,106.6540",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Airport Rental Location"
                        },
                        new
                        {
                            Id = 3,
                            Address = "12 Le Loi St, District 1, Ho Chi Minh City",
                            Coordinates = "10.7760,106.7030",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LocationId = 0,
                            Name = "District 1 Rental Location"
                        },
                        new
                        {
                            Id = 4,
                            Address = "89 Nguyen Van Linh St, District 7, Ho Chi Minh City",
                            Coordinates = "10.7298,106.7219",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LocationId = 0,
                            Name = "District 7 Rental Location"
                        },
                        new
                        {
                            Id = 5,
                            Address = "27 Dinh Bo Linh St, Binh Thanh District, Ho Chi Minh City",
                            Coordinates = "10.8123,106.7098",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LocationId = 0,
                            Name = "Binh Thanh Rental Location"
                        },
                        new
                        {
                            Id = 6,
                            Address = "101 Vo Van Ngan St, Thu Duc City",
                            Coordinates = "10.8502,106.7549",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LocationId = 0,
                            Name = "Thu Duc Rental Location"
                        },
                        new
                        {
                            Id = 7,
                            Address = "35 Hoang Van Thu St, Tan Binh District, Ho Chi Minh City",
                            Coordinates = "10.8015,106.6521",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LocationId = 0,
                            Name = "Tan Binh Rental Location"
                        },
                        new
                        {
                            Id = 8,
                            Address = "58 Phan Xich Long St, Phu Nhuan District, Ho Chi Minh City",
                            Coordinates = "10.7998,106.6825",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LocationId = 0,
                            Name = "Phu Nhuan Rental Location"
                        },
                        new
                        {
                            Id = 9,
                            Address = "245 Quang Trung St, Go Vap District, Ho Chi Minh City",
                            Coordinates = "10.8412,106.6647",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LocationId = 0,
                            Name = "Go Vap Rental Location"
                        },
                        new
                        {
                            Id = 10,
                            Address = "500 Kinh Duong Vuong St, Binh Tan District, Ho Chi Minh City",
                            Coordinates = "10.7487,106.6032",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LocationId = 0,
                            Name = "Binh Tan Rental Location"
                        });
                });

            modelBuilder.Entity("Repository.Entities.RentalOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualReturnTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int?>("CitizenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DamageFee")
                        .HasColumnType("float");

                    b.Property<string>("DamageNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Discount")
                        .HasColumnType("int");

                    b.Property<int?>("DriverLicenseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpectedReturnTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("ExtraFee")
                        .HasColumnType("float");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PickupTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RentalContactId")
                        .HasColumnType("int");

                    b.Property<int>("RentalLocationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double?>("SubTotal")
                        .HasColumnType("float");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("WithDriver")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CitizenId")
                        .IsUnique()
                        .HasFilter("[CitizenId] IS NOT NULL");

                    b.HasIndex("DriverLicenseId")
                        .IsUnique()
                        .HasFilter("[DriverLicenseId] IS NOT NULL");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasFilter("[PaymentId] IS NOT NULL");

                    b.HasIndex("RentalContactId")
                        .IsUnique()
                        .HasFilter("[RentalContactId] IS NOT NULL");

                    b.HasIndex("RentalLocationId");

                    b.HasIndex("UserId");

                    b.ToTable("RentalOrders");
                });

            modelBuilder.Entity("Repository.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmEmailToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RentalLocationId")
                        .HasColumnType("int");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RentalLocationId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            FullName = "Admin User",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Password = "1",
                            PasswordHash = "$2a$12$z.y2vdQFkt/drkj6yzAXm.6v/rirvWIaw1tXyIgvR7dki1roEfLXm",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff@gmail.com",
                            FullName = "Staff User",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Password = "1",
                            PasswordHash = "$2a$12$z.y2vdQFkt/drkj6yzAXm.6v/rirvWIaw1tXyIgvR7dki1roEfLXm",
                            RentalLocationId = 1,
                            Role = "Staff"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer@gmail.com",
                            FullName = "Customer User",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Password = "1",
                            PasswordHash = "$2a$12$z.y2vdQFkt/drkj6yzAXm.6v/rirvWIaw1tXyIgvR7dki1roEfLXm",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 4,
                            Address = "123 Tran Hung Dao St, Ho Chi Minh City",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "duongduy12314@gmail.com",
                            FullName = "Customer User 1",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Password = "1",
                            PasswordHash = "$2a$12$examplehash4",
                            PhoneNumber = "0945353500",
                            RentalLocationId = 1,
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 5,
                            Address = "456 Nguyen Cuu Phuc St, Ho Chi Minh City",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer2@gmail.com",
                            FullName = "Customer User 2",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Password = "1",
                            PasswordHash = "$2a$12$examplehash5",
                            PhoneNumber = "0901000005",
                            RentalLocationId = 2,
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 6,
                            Address = "789 Le Lai St, Ho Chi Minh City",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff1@gmail.com",
                            FullName = "Staff User 1",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Password = "1",
                            PasswordHash = "$2a$12$examplehash6",
                            PhoneNumber = "0901000006",
                            RentalLocationId = 1,
                            Role = "Staff"
                        },
                        new
                        {
                            Id = 7,
                            Address = "101 Nguyen Van Linh St, District 7, Ho Chi Minh City",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff2@gmail.com",
                            FullName = "Staff User 2",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Password = "1",
                            PasswordHash = "$2a$12$examplehash7",
                            PhoneNumber = "0901000007",
                            RentalLocationId = 2,
                            Role = "Staff"
                        },
                        new
                        {
                            Id = 8,
                            Address = "202 Le Loi St, District 1, Ho Chi Minh City",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer3@gmail.com",
                            FullName = "Customer User 3",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Password = "1",
                            PasswordHash = "$2a$12$examplehash8",
                            PhoneNumber = "0901000008",
                            RentalLocationId = 3,
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 9,
                            Address = "303 Vo Van Tan St, District 3, Ho Chi Minh City",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff3@gmail.com",
                            FullName = "Staff User 3",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Password = "1",
                            PasswordHash = "$2a$12$examplehash9",
                            PhoneNumber = "0901000009",
                            RentalLocationId = 3,
                            Role = "Staff"
                        },
                        new
                        {
                            Id = 10,
                            Address = "404 Nguyen Trai St, District 5, Ho Chi Minh City",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer4@gmail.com",
                            FullName = "Customer User 4",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Password = "1",
                            PasswordHash = "$2a$12$examplehash10",
                            PhoneNumber = "0901000010",
                            RentalLocationId = 4,
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("Repository.Entities.CarDeliveryHistory", b =>
                {
                    b.HasOne("Repository.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", "Customer")
                        .WithMany("CarDeliveryHistories")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.RentalLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.RentalOrder", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Customer");

                    b.Navigation("Location");

                    b.Navigation("Order");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Repository.Entities.CarRentalLocation", b =>
                {
                    b.HasOne("Repository.Entities.Car", "Car")
                        .WithMany("CarRentalLocations")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.RentalLocation", "Location")
                        .WithMany("CarRentalLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Repository.Entities.CarReturnHistory", b =>
                {
                    b.HasOne("Repository.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.RentalLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.RentalOrder", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Customer");

                    b.Navigation("Location");

                    b.Navigation("Order");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Repository.Entities.Feedback", b =>
                {
                    b.HasOne("Repository.Entities.RentalOrder", "RentalOrder")
                        .WithMany()
                        .HasForeignKey("RentalOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany("Feedback")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Payment", b =>
                {
                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.RentalContact", b =>
                {
                    b.HasOne("Repository.Entities.User", null)
                        .WithMany("RentalContacts")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Repository.Entities.RentalOrder", b =>
                {
                    b.HasOne("Repository.Entities.Car", "Car")
                        .WithMany("RentalOrders")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.CitizenId", "CitizenIdNavigation")
                        .WithOne("RentalOrder")
                        .HasForeignKey("Repository.Entities.RentalOrder", "CitizenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Repository.Entities.DriverLicense", "DriverLicense")
                        .WithOne("RentalOrder")
                        .HasForeignKey("Repository.Entities.RentalOrder", "DriverLicenseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Repository.Entities.Payment", "Payment")
                        .WithOne("RentalOrder")
                        .HasForeignKey("Repository.Entities.RentalOrder", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Repository.Entities.RentalContact", "RentalContact")
                        .WithOne("RentalOrder")
                        .HasForeignKey("Repository.Entities.RentalOrder", "RentalContactId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Repository.Entities.RentalLocation", "RentalLocation")
                        .WithMany("RentalOrders")
                        .HasForeignKey("RentalLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany("RentalOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("CitizenIdNavigation");

                    b.Navigation("DriverLicense");

                    b.Navigation("Payment");

                    b.Navigation("RentalContact");

                    b.Navigation("RentalLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.User", b =>
                {
                    b.HasOne("Repository.Entities.RentalLocation", "RentalLocation")
                        .WithMany("Users")
                        .HasForeignKey("RentalLocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RentalLocation");
                });

            modelBuilder.Entity("Repository.Entities.Car", b =>
                {
                    b.Navigation("CarRentalLocations");

                    b.Navigation("RentalOrders");
                });

            modelBuilder.Entity("Repository.Entities.CitizenId", b =>
                {
                    b.Navigation("RentalOrder")
                        .IsRequired();
                });

            modelBuilder.Entity("Repository.Entities.DriverLicense", b =>
                {
                    b.Navigation("RentalOrder")
                        .IsRequired();
                });

            modelBuilder.Entity("Repository.Entities.Payment", b =>
                {
                    b.Navigation("RentalOrder");
                });

            modelBuilder.Entity("Repository.Entities.RentalContact", b =>
                {
                    b.Navigation("RentalOrder");
                });

            modelBuilder.Entity("Repository.Entities.RentalLocation", b =>
                {
                    b.Navigation("CarRentalLocations");

                    b.Navigation("RentalOrders");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Repository.Entities.User", b =>
                {
                    b.Navigation("CarDeliveryHistories");

                    b.Navigation("Feedback");

                    b.Navigation("Payments");

                    b.Navigation("RentalContacts");

                    b.Navigation("RentalOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
