// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Context;

#nullable disable

namespace Repository.Context.Migrations
{
    [DbContext(typeof(EVSDbContext))]
    partial class EVSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repository.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryDuration")
                        .HasColumnType("int");

                    b.Property<string>("BatteryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DepositCarAmount")
                        .HasColumnType("float");

                    b.Property<double>("DepositOrderAmount")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RentPricePer4Hour")
                        .HasColumnType("float");

                    b.Property<double>("RentPricePer4HourWithDriver")
                        .HasColumnType("float");

                    b.Property<double>("RentPricePer8Hour")
                        .HasColumnType("float");

                    b.Property<double>("RentPricePer8HourWithDriver")
                        .HasColumnType("float");

                    b.Property<double>("RentPricePerDay")
                        .HasColumnType("float");

                    b.Property<double>("RentPricePerDayWithDriver")
                        .HasColumnType("float");

                    b.Property<int?>("RentalLocationId")
                        .HasColumnType("int");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<string>("SizeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrunkCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RentalLocationId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatteryDuration = 350,
                            BatteryType = "Lithium-Ion",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepositCarAmount = 2000000.0,
                            DepositOrderAmount = 200000.0,
                            ImageUrl = "https://example.com/tesla_model_3.jpg",
                            ImageUrl2 = "https://example.com/tesla_model_3.jpg",
                            ImageUrl3 = "https://example.com/tesla_model_3.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Model = "Tesla Model 3",
                            Name = "Model 3",
                            RentPricePer4Hour = 300000.0,
                            RentPricePer4HourWithDriver = 400000.0,
                            RentPricePer8Hour = 500000.0,
                            RentPricePer8HourWithDriver = 700000.0,
                            RentPricePerDay = 1000000.0,
                            RentPricePerDayWithDriver = 1400000.0,
                            RentalLocationId = 1,
                            Seats = 5,
                            SizeType = "Sedan",
                            TrunkCapacity = 425
                        },
                        new
                        {
                            Id = 2,
                            BatteryDuration = 240,
                            BatteryType = "Lithium-Ion",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepositCarAmount = 4500000.0,
                            DepositOrderAmount = 160000.0,
                            ImageUrl = "https://example.com/nissan_leaf.jpg",
                            ImageUrl2 = "https://example.com/nissan_leaf.jpg",
                            ImageUrl3 = "https://example.com/nissan_leaf.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Model = "Nissan Leaf",
                            Name = "Leaf",
                            RentPricePer4Hour = 250000.0,
                            RentPricePer4HourWithDriver = 350000.0,
                            RentPricePer8Hour = 450000.0,
                            RentPricePer8HourWithDriver = 600000.0,
                            RentPricePerDay = 800000.0,
                            RentPricePerDayWithDriver = 1200000.0,
                            RentalLocationId = 2,
                            Seats = 5,
                            SizeType = "Hatchback",
                            TrunkCapacity = 435
                        },
                        new
                        {
                            Id = 3,
                            BatteryDuration = 259,
                            BatteryType = "Lithium-Ion",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepositCarAmount = 3400000.0,
                            DepositOrderAmount = 180000.0,
                            ImageUrl = "https://example.com/chevrolet_bolt_ev.jpg",
                            ImageUrl2 = "https://example.com/chevrolet_bolt_ev.jpg",
                            ImageUrl3 = "https://example.com/chevrolet_bolt_ev.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Model = "Chevrolet Bolt EV",
                            Name = "Bolt EV",
                            RentPricePer4Hour = 280000.0,
                            RentPricePer4HourWithDriver = 380000.0,
                            RentPricePer8Hour = 480000.0,
                            RentPricePer8HourWithDriver = 650000.0,
                            RentPricePerDay = 900000.0,
                            RentPricePerDayWithDriver = 1300000.0,
                            RentalLocationId = 3,
                            Seats = 5,
                            SizeType = "Hatchback",
                            TrunkCapacity = 478
                        },
                        new
                        {
                            Id = 4,
                            BatteryDuration = 153,
                            BatteryType = "Lithium-Ion",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepositCarAmount = 20000000.0,
                            DepositOrderAmount = 110000.0,
                            ImageUrl = "https://example.com/bmw_i3.jpg",
                            ImageUrl2 = "https://example.com/bmw_i3.jpg",
                            ImageUrl3 = "https://example.com/bmw_i3.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Model = "BMW i3",
                            Name = "i3",
                            RentPricePer4Hour = 350000.0,
                            RentPricePer4HourWithDriver = 450000.0,
                            RentPricePer8Hour = 550000.0,
                            RentPricePer8HourWithDriver = 750000.0,
                            RentPricePerDay = 1100000.0,
                            RentPricePerDayWithDriver = 1500000.0,
                            RentalLocationId = 3,
                            Seats = 4,
                            SizeType = "Hatchback",
                            TrunkCapacity = 260
                        },
                        new
                        {
                            Id = 5,
                            BatteryDuration = 222,
                            BatteryType = "Lithium-Ion",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepositCarAmount = 17000000.0,
                            DepositOrderAmount = 225000.0,
                            ImageUrl = "https://example.com/audi_e_tron.jpg",
                            ImageUrl2 = "https://example.com/audi_e_tron.jpg",
                            ImageUrl3 = "https://example.com/audi_e_tron.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Model = "Audi e-tron",
                            Name = "e-tron",
                            RentPricePer4Hour = 450000.0,
                            RentPricePer4HourWithDriver = 600000.0,
                            RentPricePer8Hour = 750000.0,
                            RentPricePer8HourWithDriver = 900000.0,
                            RentPricePerDay = 1500000.0,
                            RentPricePerDayWithDriver = 2000000.0,
                            RentalLocationId = 4,
                            Seats = 5,
                            SizeType = "SUV",
                            TrunkCapacity = 660
                        },
                        new
                        {
                            Id = 6,
                            BatteryDuration = 258,
                            BatteryType = "Lithium-Ion",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepositCarAmount = 6000000.0,
                            DepositOrderAmount = 175000.0,
                            ImageUrl = "https://example.com/hyundai_kona_electric.jpg",
                            ImageUrl2 = "https://example.com/hyundai_kona_electric.jpg",
                            ImageUrl3 = "https://example.com/hyundai_kona_electric.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Model = "Hyundai Kona Electric",
                            Name = "Kona Electric",
                            RentPricePer4Hour = 290000.0,
                            RentPricePer4HourWithDriver = 390000.0,
                            RentPricePer8Hour = 490000.0,
                            RentPricePer8HourWithDriver = 640000.0,
                            RentPricePerDay = 950000.0,
                            RentPricePerDayWithDriver = 1350000.0,
                            RentalLocationId = 2,
                            Seats = 5,
                            SizeType = "SUV",
                            TrunkCapacity = 332
                        });
                });

            modelBuilder.Entity("Repository.Entities.CarDeliveryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryLevelStart")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OdometerStart")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleConditionStart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("CarDeliveryHistories");
                });

            modelBuilder.Entity("Repository.Entities.CarReturnHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryLevelEnd")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OdometerEnd")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleConditionEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("OrderId");

                    b.ToTable("CarReturnHistories");
                });

            modelBuilder.Entity("Repository.Entities.CitizenId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CitizenIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CitizenIds");
                });

            modelBuilder.Entity("Repository.Entities.DriverLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DriverLicenses");
                });

            modelBuilder.Entity("Repository.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RentalOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RentalOrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Repository.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("BillingImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<int?>("RentalOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TxnRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RentalOrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Repository.Entities.RentalLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RentalLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "209 Nguyễn Văn Tăng, Long Thạnh Mỹ, Thủ Đức, TP.HCM",
                            Coordinates = "10.84274, 106.8198",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "EVStation Nguyễn Văn Tăng"
                        },
                        new
                        {
                            Id = 2,
                            Address = "447 Lê Văn Việt, Thủ Đức, TP.HCM",
                            Coordinates = "10.84529, 106.7933",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "EVStation Lê Văn Việt"
                        },
                        new
                        {
                            Id = 3,
                            Address = "39634 Kha Vạn Cân, Linh Chiểu, Thủ Đức, TP.HCM",
                            Coordinates = "10.856468, 106.756518",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "EVStation Kha Vạn Cân"
                        },
                        new
                        {
                            Id = 4,
                            Address = "190 Võ Văn Ngân, Bình Thọ, Thủ Đức, TP.HCM",
                            Coordinates = "10.850805, 106.763773",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "EVStation Võ Văn Ngân"
                        });
                });

            modelBuilder.Entity("Repository.Entities.RentalOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualReturnTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("ContactImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactImageUrl2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DamageFee")
                        .HasColumnType("float");

                    b.Property<string>("DamageNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DepositCar")
                        .HasColumnType("float");

                    b.Property<double?>("DepositOrder")
                        .HasColumnType("float");

                    b.Property<double?>("Discount")
                        .HasColumnType("float");

                    b.Property<DateTime>("ExpectedReturnTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("ExtraFee")
                        .HasColumnType("float");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PickupTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RentalLocationId")
                        .HasColumnType("int");

                    b.Property<string>("ReportNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double?>("SubTotal")
                        .HasColumnType("float");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("WithDriver")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("RentalLocationId");

                    b.HasIndex("UserId");

                    b.ToTable("RentalOrders");
                });

            modelBuilder.Entity("Repository.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CitizenId")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmEmailToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DriverLicenseId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Point")
                        .HasColumnType("int");

                    b.Property<int?>("RentalLocationId")
                        .HasColumnType("int");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId")
                        .IsUnique()
                        .HasFilter("[CitizenId] IS NOT NULL");

                    b.HasIndex("DriverLicenseId")
                        .IsUnique()
                        .HasFilter("[DriverLicenseId] IS NOT NULL");

                    b.HasIndex("RentalLocationId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            FullName = "Admin User",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Password = "1",
                            PasswordHash = "$2a$12$z.y2vdQFkt/drkj6yzAXm.6v/rirvWIaw1tXyIgvR7dki1roEfLXm",
                            PhoneNumber = "0123456789",
                            Point = 100,
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff@gmail.com",
                            FullName = "Staff User",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Password = "1",
                            PasswordHash = "$2a$12$z.y2vdQFkt/drkj6yzAXm.6v/rirvWIaw1tXyIgvR7dki1roEfLXm",
                            PhoneNumber = "0123456789",
                            Point = 100,
                            RentalLocationId = 1,
                            Role = "Staff"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer@gmail.com",
                            FullName = "Customer User",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Password = "1",
                            PasswordHash = "$2a$12$z.y2vdQFkt/drkj6yzAXm.6v/rirvWIaw1tXyIgvR7dki1roEfLXm",
                            PhoneNumber = "0123456789",
                            Point = 100,
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff2@gmail.com",
                            FullName = "Staff User",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Password = "1",
                            PasswordHash = "$2a$12$z.y2vdQFkt/drkj6yzAXm.6v/rirvWIaw1tXyIgvR7dki1roEfLXm",
                            PhoneNumber = "0123456789",
                            Point = 100,
                            RentalLocationId = 2,
                            Role = "Staff"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff3@gmail.com",
                            FullName = "Staff User",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Password = "1",
                            PasswordHash = "$2a$12$z.y2vdQFkt/drkj6yzAXm.6v/rirvWIaw1tXyIgvR7dki1roEfLXm",
                            PhoneNumber = "0123456789",
                            Point = 100,
                            RentalLocationId = 3,
                            Role = "Staff"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff4@gmail.com",
                            FullName = "Staff User",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Password = "1",
                            PasswordHash = "$2a$12$z.y2vdQFkt/drkj6yzAXm.6v/rirvWIaw1tXyIgvR7dki1roEfLXm",
                            PhoneNumber = "0123456789",
                            Point = 100,
                            RentalLocationId = 4,
                            Role = "Staff"
                        });
                });

            modelBuilder.Entity("Repository.Entities.Car", b =>
                {
                    b.HasOne("Repository.Entities.RentalLocation", "RentalLocation")
                        .WithMany("Cars")
                        .HasForeignKey("RentalLocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RentalLocation");
                });

            modelBuilder.Entity("Repository.Entities.CarDeliveryHistory", b =>
                {
                    b.HasOne("Repository.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.RentalOrder", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", null)
                        .WithMany("CarDeliveryHistories")
                        .HasForeignKey("UserId");

                    b.Navigation("Car");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Repository.Entities.CarReturnHistory", b =>
                {
                    b.HasOne("Repository.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.RentalOrder", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Repository.Entities.Feedback", b =>
                {
                    b.HasOne("Repository.Entities.RentalOrder", "RentalOrder")
                        .WithMany()
                        .HasForeignKey("RentalOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany("Feedback")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Payment", b =>
                {
                    b.HasOne("Repository.Entities.RentalOrder", "RentalOrder")
                        .WithMany("Payments")
                        .HasForeignKey("RentalOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RentalOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.RentalOrder", b =>
                {
                    b.HasOne("Repository.Entities.Car", "Car")
                        .WithMany("RentalOrders")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.RentalLocation", "RentalLocation")
                        .WithMany("RentalOrders")
                        .HasForeignKey("RentalLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany("RentalOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("RentalLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.User", b =>
                {
                    b.HasOne("Repository.Entities.CitizenId", "CitizenIdNavigation")
                        .WithOne("User")
                        .HasForeignKey("Repository.Entities.User", "CitizenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Repository.Entities.DriverLicense", "DriverLicense")
                        .WithOne("User")
                        .HasForeignKey("Repository.Entities.User", "DriverLicenseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Repository.Entities.RentalLocation", "RentalLocation")
                        .WithMany("Users")
                        .HasForeignKey("RentalLocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CitizenIdNavigation");

                    b.Navigation("DriverLicense");

                    b.Navigation("RentalLocation");
                });

            modelBuilder.Entity("Repository.Entities.Car", b =>
                {
                    b.Navigation("RentalOrders");
                });

            modelBuilder.Entity("Repository.Entities.CitizenId", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Repository.Entities.DriverLicense", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Repository.Entities.RentalLocation", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("RentalOrders");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Repository.Entities.RentalOrder", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Repository.Entities.User", b =>
                {
                    b.Navigation("CarDeliveryHistories");

                    b.Navigation("Feedback");

                    b.Navigation("Payments");

                    b.Navigation("RentalOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
